### ISSUE TITLE
Redisson Tomcat Manager

### ISSUE THREAD

**Issue by mrniko** [chexagon/redis-session-manager#7]
Hi!

It's nice to see Redisson based session manager. Redisson already provides tomcat 8 manager implementation. We could discuss difference between this and Redisson's implementation and made it better. Can we?

**Comment by scubasau** [comment]
Sure. This session manager was written before redisson included its own version. We've been using this in our production systems for quite some time with no (noticeable!) problems. Since we follow the philosophy of 'if it ain't broke...' we have not evaluated the provided redisson version to compare/contrast.

Feel free to adopt anything this session manager does into the redisson version or open new issues if there's something missing from this package.
